/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu Sep 28 16:08:00 CDT 2017
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo;

/*
 * For Table Articulo
 */
public class Articulo implements java.io.Serializable, Cloneable {
    private ArticuloKey _key = new ArticuloKey();

    /* claveArticulo, PK */
    protected String clavearticulo;

    /* descripcion */
    protected String descripcion;

    /* precio */
    protected double precio;

    /* existencias */
    protected int existencias;

    /* Return the key object. */
    public ArticuloKey getKeyObject() {
        return _key;
    }

    /* claveArticulo, PK */
    public String getClavearticulo() {
        return clavearticulo;
    }

    /* claveArticulo, PK */
    public void setClavearticulo(String clavearticulo) {
        this.clavearticulo = clavearticulo;
        _key.setClavearticulo(clavearticulo);
    }

    /* descripcion */
    public String getDescripcion() {
        return descripcion;
    }

    /* descripcion */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /* precio */
    public double getPrecio() {
        return precio;
    }

    /* precio */
    public void setPrecio(double precio) {
        this.precio = precio;
    }

    /* existencias */
    public int getExistencias() {
        return existencias;
    }

    /* existencias */
    public void setExistencias(int existencias) {
        this.existencias = existencias;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Articulo))
            return false;

        Articulo bean = (Articulo) obj;

        if (this.clavearticulo == null) {
            if (bean.clavearticulo != null)
                return false;
        }
        else if (!this.clavearticulo.equals(bean.clavearticulo)) 
            return false;

        if (this.descripcion == null) {
            if (bean.descripcion != null)
                return false;
        }
        else if (!this.descripcion.equals(bean.descripcion)) 
            return false;

        if (this.precio != bean.precio)
            return false;

        if (this.existencias != bean.existencias)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Articulo bean = new Articulo();
        bean.clavearticulo = this.clavearticulo;
        bean.descripcion = this.descripcion;
        bean.precio = this.precio;
        bean.existencias = this.existencias;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("clavearticulo").append(" = ").append(clavearticulo).append("]").append(sep);
        sb.append("[").append("descripcion").append(" = ").append(descripcion).append("]").append(sep);
        sb.append("[").append("precio").append(" = ").append(precio).append("]").append(sep);
        sb.append("[").append("existencias").append(" = ").append(existencias).append("]").append(sep);
        return sb.toString();
    }
}