/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu Sep 28 16:08:00 CDT 2017
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo;

public class ArticuloKey implements java.io.Serializable, Cloneable {
    /* claveArticulo */
    protected String clavearticulo;

    /* claveArticulo */
    public String getClavearticulo() {
        return clavearticulo;
    }

    /* claveArticulo */
    public void setClavearticulo(String clavearticulo) {
        this.clavearticulo = clavearticulo;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (clavearticulo != null)  
            hashCode += clavearticulo.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof ArticuloKey))
            return false;

        ArticuloKey key = (ArticuloKey) obj;

        if (this.clavearticulo == null) {
            if (key.clavearticulo != null)
                return false;
        }
        else if (!this.clavearticulo.equals(key.clavearticulo)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        ArticuloKey key = new ArticuloKey();
        key.clavearticulo = this.clavearticulo;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("clavearticulo").append(" = ").append(clavearticulo).append("]");
        return sb.toString();
    }
}