/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu Sep 28 16:08:00 CDT 2017
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo;

/*
 * For Table Movimientos
 */
public class Movimientos implements java.io.Serializable, Cloneable {
    private MovimientosKey _key = new MovimientosKey();

    /* folio, PK */
    protected String folio;

    /* fecha */
    protected java.util.Date fecha;

    /* tipoMov */
    protected String tipomov;

    /* cantidad */
    protected int cantidad;

    /* claveArticulo */
    protected String clavearticulo;

    /* Return the key object. */
    public MovimientosKey getKeyObject() {
        return _key;
    }

    /* folio, PK */
    public String getFolio() {
        return folio;
    }

    /* folio, PK */
    public void setFolio(String folio) {
        this.folio = folio;
        _key.setFolio(folio);
    }

    /* fecha */
    public java.util.Date getFecha() {
        return fecha;
    }

    /* fecha */
    public void setFecha(java.util.Date fecha) {
        this.fecha = fecha;
    }

    /* tipoMov */
    public String getTipomov() {
        return tipomov;
    }

    /* tipoMov */
    public void setTipomov(String tipomov) {
        this.tipomov = tipomov;
    }

    /* cantidad */
    public int getCantidad() {
        return cantidad;
    }

    /* cantidad */
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    /* claveArticulo */
    public String getClavearticulo() {
        return clavearticulo;
    }

    /* claveArticulo */
    public void setClavearticulo(String clavearticulo) {
        this.clavearticulo = clavearticulo;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Movimientos))
            return false;

        Movimientos bean = (Movimientos) obj;

        if (this.folio == null) {
            if (bean.folio != null)
                return false;
        }
        else if (!this.folio.equals(bean.folio)) 
            return false;

        if (this.fecha == null) {
            if (bean.fecha != null)
                return false;
        }
        else if (!this.fecha.equals(bean.fecha)) 
            return false;

        if (this.tipomov == null) {
            if (bean.tipomov != null)
                return false;
        }
        else if (!this.tipomov.equals(bean.tipomov)) 
            return false;

        if (this.cantidad != bean.cantidad)
            return false;

        if (this.clavearticulo == null) {
            if (bean.clavearticulo != null)
                return false;
        }
        else if (!this.clavearticulo.equals(bean.clavearticulo)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Movimientos bean = new Movimientos();
        bean.folio = this.folio;
        if (this.fecha != null)
            bean.fecha = (java.util.Date) this.fecha.clone();
        bean.tipomov = this.tipomov;
        bean.cantidad = this.cantidad;
        bean.clavearticulo = this.clavearticulo;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("folio").append(" = ").append(folio).append("]").append(sep);
        sb.append("[").append("fecha").append(" = ").append(fecha).append("]").append(sep);
        sb.append("[").append("tipomov").append(" = ").append(tipomov).append("]").append(sep);
        sb.append("[").append("cantidad").append(" = ").append(cantidad).append("]").append(sep);
        sb.append("[").append("clavearticulo").append(" = ").append(clavearticulo).append("]").append(sep);
        return sb.toString();
    }
}