/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu Sep 28 16:08:00 CDT 2017
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo;

public class MovimientosKey implements java.io.Serializable, Cloneable {
    /* folio */
    protected String folio;

    /* folio */
    public String getFolio() {
        return folio;
    }

    /* folio */
    public void setFolio(String folio) {
        this.folio = folio;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (folio != null)  
            hashCode += folio.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof MovimientosKey))
            return false;

        MovimientosKey key = (MovimientosKey) obj;

        if (this.folio == null) {
            if (key.folio != null)
                return false;
        }
        else if (!this.folio.equals(key.folio)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        MovimientosKey key = new MovimientosKey();
        key.folio = this.folio;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("folio").append(" = ").append(folio).append("]");
        return sb.toString();
    }
}