/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu Sep 28 16:08:00 CDT 2017
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import com.ipn.mx.modelo.*;
import com.ipn.mx.modelo.dao.ArticuloDAO;

/**
 * This class provides methods to populate DB Table of Articulo
 */
public class ArticuloDAOImpl implements ArticuloDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Articulo ("
        + "claveArticulo, descripcion, precio, existencias"
        + ") VALUES (?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "claveArticulo, descripcion, precio, existencias "
        + "FROM Articulo WHERE "
        + "claveArticulo = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Articulo SET "
        + "descripcion = ?, precio = ?, existencias = ? "
        + "WHERE "
        + "claveArticulo = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Articulo WHERE "
        + "claveArticulo = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Articulo bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setString(1, bean.getClavearticulo());
            ps.setString(2, bean.getDescripcion());
            ps.setDouble(3, bean.getPrecio());
            ps.setInt(4, bean.getExistencias());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Articulo load(ArticuloKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setString(1, key.getClavearticulo());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Articulo) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Articulo bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getDescripcion());
            ps.setDouble(2, bean.getPrecio());
            ps.setInt(3, bean.getExistencias());
            ps.setString(4, bean.getClavearticulo());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(ArticuloKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setString(1, key.getClavearticulo());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Articulo> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Articulo>();
        while (rs.next()) {
            Articulo bean = new Articulo();
            bean.setClavearticulo(rs.getString("claveArticulo"));
            bean.setDescripcion(rs.getString("descripcion"));
            bean.setPrecio(rs.getDouble("precio"));
            bean.setExistencias(rs.getInt("existencias"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}