/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu Sep 28 16:08:00 CDT 2017
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import com.ipn.mx.modelo.*;
import com.ipn.mx.modelo.dao.MovimientosDAO;

/**
 * This class provides methods to populate DB Table of Movimientos
 */
public class MovimientosDAOImpl implements MovimientosDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Movimientos ("
        + "folio, fecha, tipoMov, cantidad, claveArticulo"
        + ") VALUES (?, ?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "folio, fecha, tipoMov, cantidad, claveArticulo "
        + "FROM Movimientos WHERE "
        + "folio = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Movimientos SET "
        + "fecha = ?, tipoMov = ?, cantidad = ?, claveArticulo = ? "
        + "WHERE "
        + "folio = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Movimientos WHERE "
        + "folio = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Movimientos bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setString(1, bean.getFolio());
            if (bean.getFecha() != null)
                ps.setDate(2, new java.sql.Date(bean.getFecha().getTime()));
            else
                ps.setNull(2, Types.DATE);
            ps.setString(3, bean.getTipomov());
            ps.setInt(4, bean.getCantidad());
            ps.setString(5, bean.getClavearticulo());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Movimientos load(MovimientosKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setString(1, key.getFolio());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Movimientos) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Movimientos bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            if (bean.getFecha() != null)
                ps.setDate(1, new java.sql.Date(bean.getFecha().getTime()));
            else
                ps.setNull(1, Types.DATE);
            ps.setString(2, bean.getTipomov());
            ps.setInt(3, bean.getCantidad());
            ps.setString(4, bean.getClavearticulo());
            ps.setString(5, bean.getFolio());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(MovimientosKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setString(1, key.getFolio());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Movimientos> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Movimientos>();
        while (rs.next()) {
            Movimientos bean = new Movimientos();
            bean.setFolio(rs.getString("folio"));
            bean.setFecha(rs.getDate("fecha"));
            bean.setTipomov(rs.getString("tipoMov"));
            bean.setCantidad(rs.getInt("cantidad"));
            bean.setClavearticulo(rs.getString("claveArticulo"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}